openapi: 3.0.1
info:
  title: monster-trumpet-archon
  x-cortex-tag: monster-trumpet-archon
  x-cortex-custom-metadata:
    alignment: chaotic-neutral
    type: celestial
    challenge_rating: 8
    legendary: true
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-trumpet-archon
      alias: github-token-test
